# give me all cycling path start and endpoints in near train station san bartalomeo in les than 10KM

prefix onto:<http://www.ontotext.com/> 
prefix ontology:<http://knowdive.disi.unitn.it/etype#>
PREFIX omgeo:<http://www.ontotext.com/owlim/geo#>

select ?road ?location ?latitude ?longitude ?address ?mylat ?mylong
where
{
    {
        select ?mylat ?mylong where {
            ?address ontology:has_street_address_GID-45807_Type-36400 ?street.
            FILTER regex(?street, "Malpensada").
            ?address ontology:has_location_GID-132_Type-36400 ?location.
            ?location ontology:has_latitude_GID-46263_Type-132 ?mylat.
            ?location ontology:has_longitude_GID-46270_Type-132 ?mylong.
        }
	}    
    ?road ontology:has_location_GID-132_Type-138 ?location.
    ?location ontology:has_latitude_GID-46263_Type-132 ?latitude.
    ?location ontology:has_longitude_GID-46270_Type-132 ?longitude.
    FILTER( omgeo:distance(?mylat, ?mylong, ?latitude,?longitude) < 5).
}